// routes/dataRoutes.js
const express = require("express");
const dataController = require("../controllers/dataController");
const router = express.Router();
const path = require("path"); 
const multer = require('multer');
const upload = multer({
    storage: multer.memoryStorage(),
    
    limits: { fileSize: 50 * 1024 * 1024 }, // 50MB limit
  });


  const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, "uploads/"),
  filename: (req, file, cb) => {
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const upload2 = multer({ storage });


router.get("/Companyno",dataController.getCompanyno)
router.post("/companysearchcriteria",dataController.getsearchdata)
router.post("/add", upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.addData)
router.post("/saveEditedData", dataController.saveEditedData);
router.post("/delete", dataController.deleteData);
router.post("/CompanyUpdate",upload.fields([
  { name: 'company_logo', maxCount: 1 },
  { name: 'authorisedSignatur', maxCount: 1 }
]),dataController.CompanyUpdate)
router.post("/UpdateCompanyImage",upload.single('company_logo'),dataController.UpdateCompanyImage)
router.post("/getCompanyData",dataController.getCompanyData)
router.get("/CompanyMappingData",dataController.getAllCompanyMappingData)
router.post("/addCompanyMappingData",dataController.addCompanyMappingData)
router.post("/companymappingsearchdata",dataController.getcompanymappingsearchdata)
router.post("/getusercompany",dataController.getusercompany)
router.post("/updcompanymapping",dataController.updcompanymapping)
router.post("/commappingdeleteData",dataController.commappingdeleteData)
router.post("/CompanyMappingUpdate", dataController.CompanyMappingUpdate)
router.post("/getCompanyMappingData",dataController.getCompanyMappingData)
router.get("/locationno",dataController.getLocationno)
router.post("/locationSearchdata",dataController.getlocationsearchdata)
router.post("/addlocationinfo",dataController.addlocationinfo)
router.post("/deletelocation",dataController.locationdeleteData)
router.post("/LocationUpdate", dataController.LocationUpdate)
router.post("/getLocationData",dataController.getLocationData)
router.post("/roleid", dataController.getroleid)
router.get("/RoleInfoData", dataController.getAllRoleInfoData)
router.post("/addRoleInfoData", dataController.AddRoleInfoData)
router.post("/Roleupdate", dataController.RolesaveEditedData)
router.post("/Rolesearchdata",dataController.getRolesearchdata)
router.post("/roledelete",dataController.roledeleteData)
router.post("/UserRole",dataController.getUserRole)
router.post("/RoleUpdates", dataController.RoleUpdate)
router.post("/getRoleData",dataController.getRoleData)
router.get("/UserRoleMappingData",dataController.getAllUserRoleMappingData)
router.post("/addUserRoleMappingData",dataController.addUserRoleMappingData)
router.post("/userrolsearchdata",dataController.getUserrolesearchdata)
router.post("/RollMappingDelete",dataController.RollMappingDelete)
router.post("/updateRoleMapping",dataController.updateRoleMapping)
router.post("/RoleMappingUpdate", dataController.RoleMappingUpdate)
router.post("/getRoleMappingData",dataController.getRoleMappingData)
router.get("/userscreenmap", dataController.getAlluserscreenmap)
router.post("/adduserscreenmap",dataController.adduserscreenmap)
router.post("/saveEditeduserscreenmap",dataController.saveEditeduserscreenmap)
router.post("/userscreenmapdeleteData",dataController.userscreenmapdeleteData)
router.post("/userscreensearchdata",dataController.getuserscreensearchdata)
router.post("/getUserPermission",dataController.getUserPermission)
router.post("/updateRoleRights",dataController.updateRoleRights)
router.post("/getRoleRightsData",dataController.getRoleRightsData)

router.post("/AttributeUpdate", dataController.AttributeUpdate)
router.post("/hdrcode", dataController.gethdrcode)

router.get("/attributedetData",dataController.getAllattributedetData)
router.post("/addattridetData",dataController.addattridetData)
router.post("/delattridetData",dataController.deleteAttriDetailData)
router.post("/updattridetData",dataController.updattridetData)
router.post("/attributeSearchdata",dataController.getattributeSearchdata)
router.post("/getGSTReport",dataController.getGSTReport)
router.post("/getDateFormat",dataController.getDateFormat)
router.post("/getAttributeData",dataController.getAttributeData)
router.post("/forgetPassword", dataController.forgetPassword)
router.post("/Passwords",dataController.Passwords)
router.post("/login", dataController.login)
router.get("/usercode",dataController.getUsercode)
router.get ("/userData", dataController.getAlluserData)
router.post("/useradd",upload.single('user_img'),dataController.userAddData)
router.post("/userupdate", dataController.UsersaveEditedData)
router.post("/userdelete", dataController.UserdeleteData)
router.post("/usersearchcriteria",dataController.getUsersearchdata)
router.post("/UpdateUserImage",upload.single('user_img'),dataController.UpdateUserImage)
router.post("/UserUpdates", upload.single('user_images'), dataController.UserUpdate)
router.post("/Userdropdown",dataController.Userdropdown)
router.post("/getUCN",dataController.getUCN)
router.post("/getUserData",dataController.getUserData)
router.post("/city", dataController.getCity)
router.post("/state", dataController.getState)
router.post("/country", dataController.getCountry)    
router.post("/status", dataController.getStatus)
router.post("/Screens",dataController.getScreens)
router.post("/Permissions",dataController.getPermissions)
router.post("/Loginorout", dataController.getLoginorout)
router.post("/gender", dataController.getGender)
router.post("/addattriData",dataController.addattrihdrData)
router.get("/Numberseries",dataController.getAllNumberseries)
router.get("/getAllNumberseries",dataController.getAllNumberseries)
router.post("/screentype",dataController.getscreentype)
router.post("/getBillFormat",dataController.getBillFormat)
router.post("/getboolean", dataController.getboolean)
router.post("/numberseriessearchdata",dataController.getnumberseriessearchdata)
router.post("/addNumberseries",dataController.addNumberseries)
router.post("/NumberSeriesUpdate",dataController.NumberSeriesUpdate)
router.post("/NumberSeriesdeleteData",dataController.numberseriesdeleteData)
router.post("/memberAddData",upload.single('Photo'),dataController.memberAddData)
router.post("/getMembershipType",dataController.getMembershipType)
router.post("/getRelationship",dataController.getRelationship)
router.post("/memberUpdate",upload.single('Photo'),dataController.memberUpdate)
router.post("/memberDeleteData", dataController.memberDeleteData)
router.post("/getAllmemberData", dataController.getAllmemberData)
router.post("/GYM_TrainerInsert", upload.single("Photo"), dataController.GYM_TrainerInsert);
router.post("/GYM_TrainerUpdate", upload.single("Photo"), dataController.GYM_TrainerUpdate)
router.post("/GYM_TrainerDelete",dataController.GYM_TrainerDelete)
router.post("/getTrainerSC",dataController.getTrainerSC)
router.post("/searchMemberData",dataController.searchMemberData)
router.post("/getCategory",dataController.getCategory)
router.post("/getDifficultyLevel",dataController.getDifficultyLevel)
router.post("/getTrainers",dataController.getTrainers)
router.post("/programInsertData",dataController.programInsertData)
router.post("/programUpdateData",dataController.programUpdateData)
router.post("/programDeleteData",dataController.programDeleteData)
router.post("/programFacultyInsertData",dataController.programFacultyInsertData)
router.post("/programFacultyUpdateData",dataController.programFacultyUpdateData)
router.post("/programFacultyDeleteData",dataController.programFacultyDeleteData)
router.post("/programExerciseInsertData",dataController.programExerciseInsertData)
router.post("/programExerciseUpdateData",dataController.programExerciseUpdateData)
router.post("/programExerciseDeleteData",dataController.programExerciseDeleteData)
router.post("/getMemberCardData",dataController.getMemberCardData)
router.post("/programSearchData",dataController.programSearchData)
router.post("/programCardData",dataController.programCardData)
router.post("/settingSaveData", dataController.settingSaveData)
router.post("/getSettingScreenData", dataController.getSettingScreenData)
router.post("/getTrainerCardData", dataController.getTrainerCardData)
router.post("/couponInsertData", dataController.couponInsertData)
router.post("/couponUpdateData", dataController.couponUpdateData)
router.post("/couponDeleteData", dataController.couponDeleteData)
router.post("/couponSearchData", dataController.couponSearchData)
router.post("/getDisType", dataController.getDisType)
router.post("/getAppPackages", dataController.getAppPackages)
router.post("/couponDashboard", dataController.couponDashboard)
router.post("/Diet_Plans_hdrInsert", dataController.Diet_Plans_hdrInsert)
router.post("/Diet_Plans_hdrUpdate", dataController.Diet_Plans_hdrUpdate)
router.post("/Diet_Plans_hdrDelete", dataController.Diet_Plans_hdrDelete)
router.post("/Diet_Plans_MealsInsert", dataController.Diet_Plans_MealsInsert)
router.post("/Diet_Plans_MealsUpdate", dataController.Diet_Plans_MealsUpdate)
router.post("/Diet_Plans_MealsDelete", dataController.Diet_Plans_MealsDelete)
router.post("/Diet_Plans_DetailsInsert", dataController.Diet_Plans_DetailsInsert)
router.post("/Diet_Plans_DetailsUpdate", dataController.Diet_Plans_DetailsUpdate)
router.post("/Diet_Plans_DetailsDelete", dataController.Diet_Plans_DetailsDelete)
router.post("/getMealType", dataController.getMealType)
router.post("/getEssentials", dataController.getEssentials)
router.post("/getDuration", dataController.getDuration)
router.post("/dietPlanSearchData", dataController.dietPlanSearchData)
router.post("/getPrograms", dataController.getPrograms)
router.post("/getPackageTypes", dataController.getPackageTypes)
router.post("/PackageInsertData", dataController.PackageInsertData)
router.post("/PackageUpdateData", dataController.PackageUpdateData)
router.post("/PackageDeleteData", dataController.PackageDeleteData)
router.post("/PackageSelectData", dataController.PackageSelectData)
router.post("/PackageViewAllData", dataController.PackageViewAllData)
router.post("/PackageSearchData", dataController.PackageSearchData)
router.post("/PackageDetailsInsertData", dataController.PackageDetailsInsertData)
router.post("/PackageDetailsUpdateData", dataController.PackageDetailsUpdateData)
router.post("/PackageDetailsDeleteData", dataController.PackageDetailsDeleteData)
router.post("/Diet_Plans_DetailsSearch", dataController.Diet_Plans_DetailsSearch)
router.post("/Diet_Plans_MealsSearch", dataController.Diet_Plans_MealsSearch)
router.post("/getDietPlanCardData", dataController.getDietPlanCardData)
router.post("/MemberShipTypeHdrInsert", dataController.MemberShipTypeHdrInsert)
router.post("/MemberShipTypeHdrUpdate", dataController.MemberShipTypeHdrUpdate)
router.post("/MemberShipTypeHdrDelete", dataController.MemberShipTypeHdrDelete)
router.post("/MemberShipTypeDetailsInsert", dataController.MemberShipTypeDetailsInsert)
router.post("/MemberShipTypeDetailsUpdate", dataController.MemberShipTypeDetailsUpdate)
router.post("/MemberShipTypeDetailsDelete", dataController.MemberShipTypeDetailsDelete)
router.post("/getMeberShipPackages", dataController.getMeberShipPackages)
router.post("/membershipSearchData", dataController.membershipSearchData)
router.post("/getMeberShipTypeName", dataController.getMeberShipTypeName)
router.post("/adminDashboardCardData", dataController.adminDashboardCardData)
router.post("/getDietPlanNameId", dataController.getDietPlanNameId)
router.post("/getMemberProgarmDetails", dataController.getMemberProgarmDetails)
router.post("/memberProgramSearchData", dataController.memberProgramSearchData)
router.post("/PaymentTransactionInsert", dataController.PaymentTransactionInsert)
router.post("/PaymentTransactionUpdate", dataController.PaymentTransactionUpdate)
router.post("/PaymentTransactionDelete", dataController.PaymentTransactionDelete)
router.post("/getPaymentPackageDetails", dataController.getPaymentPackageDetails)
router.post("/getPaymentProgramDetails", dataController.getPaymentProgramDetails)
router.post("/applyCouponPayment", dataController.applyCouponPayment)
router.post("/getSMTPPorts", dataController.getSMTPPorts)
router.post("/getSMSProviders", dataController.getSMSProviders)
router.post("/getCountryCodes", dataController.getCountryCodes)
router.post("/getWhatsappProviders", dataController.getWhatsappProviders)
router.post("/getSSLTypes", dataController.getSSLTypes)
router.post("/EmailConfiInsert", dataController.EmailConfiInsert)
router.post("/SMSConfiInsert", dataController.SMSConfiInsert)
router.post("/WhatsappSettingsInsert", dataController.WhatsappSettingsInsert)
router.post("/reportCardDataPayment", dataController.reportCardDataPayment)
router.post("/reportPackageRevenue", dataController.reportPackageRevenue)
router.post("/couponUsageStatistics", dataController.couponUsageStatistics)
router.post("/getDashboardKPI", dataController.getDashboardKPI)
router.post("/getRevenueTrend", dataController.getRevenueTrend)
router.post("/getPaymentMethodDistribution", dataController.getPaymentMethodDistribution)
router.post("/getRecentPayments", dataController.getRecentPayments)
router.post("/getPaymentHistory", dataController.getPaymentHistory)
router.post("/getNewMemberRegistration", dataController.getNewMemberRegistration)
router.post("/getPaymentReceived", dataController.getPaymentReceived)
router.post("/getWorkoutProgramAssigned", dataController.getWorkoutProgramAssigned)
router.post("/getMemberDropDown", dataController.getMemberDropDown)
router.post("/getMemberDetail", dataController.getMemberDetail)




module.exports = router;